[pytest]
markers = 
    smoke: mark a test as a smoke test
    slow: mark a test as a slow test
    format: mark a test as a format test

log_cli = True
log_cli_level = INFO 
addopts = -v -s --html=reports/my_report.html --self-contained-html
